### ISSUE TITLE
Android 6.0下在插件中发Notification会导致插件系统崩溃

### ISSUE THREAD

**Issue by cnzx219** [DroidPluginTeam/DroidPlugin#145]
Android 6.0下在插件中发Notification会导致插件系统崩溃

原因是给notification指定的icon中，未找到图标

```
03-15 18:59:39.149  7068  7068 E MyCrashHandler: uncaughtExceptionandroid.app.RemoteServiceException: Bad notification posted from package com.example.TestPlugin: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.qihoo.secstore id=0x7f0200d8) visible user=0 num=26 )
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at android.os.Looper.loop(Looper.java:148)
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at android.app.ActivityThread.main(ActivityThread.java:5417)
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at java.lang.reflect.Method.invoke(Native Method)
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-15 18:59:39.149  7068  7068 E MyCrashHandler:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

在插件中定位问题在hook的时候没有将 插件发出的广播 识别出来。代码的位置在如图：

![bug](https://cloud.githubusercontent.com/assets/1757180/13775657/b85a5fe4-eae0-11e5-8330-bc5519edc040.png)

在Android 6.0中，之前的判断策略全部失效，并且多了一个mSmallIcon的内部变量，指向了插件的资源，导致在系统中崩溃。

请Andy大神尽快修复一下吧，多谢

**Comment by cmzy** [comment]
fixed on https://github.com/DroidPluginTeam/DroidPlugin/commit/87bdd4c2049859852a7472f5365d0ff79c4201bd
