### ISSUE TITLE
插件有定义Application的情况，怎么整？

### ISSUE THREAD

**Issue by heagoo** [DroidPluginTeam/DroidPlugin#176]
如果插件有自定义的Application，应用起不来，会报告：
Multiple instances of the Application object were created
有办法绕过去吗？Thanks!

**Comment by JackCho** [comment]
有更多的log么

**Comment by heagoo** [comment]
跑Facebook的时候报错了：

E/ACRA    (28059): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.facebook.katana/com.facebook.nodex.startup.splashscreen.NodexSplashActivity}: java.lang.RuntimeException: Unable to instantiate application com.facebook.katana.app.FacebookApplication: java.lang.IllegalStateException: Multiple instances of the Application object were created.
E/ACRA    (28059): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
E/ACRA    (28059): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
E/ACRA    (28059): 	at android.app.ActivityThread.access$800(ActivityThread.java:154)
E/ACRA    (28059): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
E/ACRA    (28059): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ACRA    (28059): 	at android.os.Looper.loop(Looper.java:135)
E/ACRA    (28059): 	at android.app.ActivityThread.main(ActivityThread.java:5336)
E/ACRA    (28059): 	at java.lang.reflect.Method.invoke(Native Method)
E/ACRA    (28059): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ACRA    (28059): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/ACRA    (28059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/ACRA    (28059): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
E/ACRA    (28059): Caused by: java.lang.RuntimeException: Unable to instantiate application com.facebook.katana.app.FacebookApplication: java.lang.IllegalStateException: Multiple instances of the Application object were created.
E/ACRA    (28059): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:572)
E/ACRA    (28059): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
E/ACRA    (28059): 	... 11 more
E/ACRA    (28059): Caused by: java.lang.IllegalStateException: Multiple instances of the Application object were created.
E/ACRA    (28059): 	at com.facebook.base.app.DelegatingApplication.e(|NO:41)
E/ACRA    (28059): 	at com.facebook.base.app.DelegatingApplication.<init>(|NO:51)
E/ACRA    (28059): 	at com.facebook.katana.app.FacebookApplication.<init>(}:73)
E/ACRA    (28059): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/ACRA    (28059): 	at java.lang.Class.newInstance(Class.java:1572)
E/ACRA    (28059): 	at android.app.Instrumentation.newApplication(Instrumentation.java:994)
E/ACRA    (28059): 	at android.app.Instrumentation.newApplication(Instrumentation.java:979)
E/ACRA    (28059): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:567)
E/ACRA    (28059): 	... 12 more

**Comment by AbnerSC** [comment]
我的插件有自定义application，运行没有问题
