### ISSUE TITLE
一个非常奇怪的问题！！！求大神解决下

### ISSUE THREAD

**Issue by hiquanta** [DroidPluginTeam/DroidPlugin#183]
直接运行官方demo可以运行自己写插件apk，但是把官方demo也当插件安装后就没法运行自己写的插件了，这是log
`FATAL EXCEPTION: main
                                                                      Process: com.example.TestPlugin, PID: 3567
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hiquanta.logisticsapp/com.hiquanta.logisticsapp.ui.LoginActivity}: java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to android.support.v7.widget.ContentFrameLayout
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                       Caused by: java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to android.support.v7.widget.ContentFrameLayout
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:470)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                                                                          at com.hiquanta.logisticsapp.base.BaseActivity.onCreate(BaseActivity.java:65)
                                                                          at android.app.Activity.performCreate(Activity.java:5933)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                          at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:110)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) `

**Comment by Hiram-Y** [comment]
这个问题解决了吗？

**Comment by yeyutianya** [comment]
这个问题解决没？

**Comment by hiquanta** [comment]
已经解决了  跟编译版本的主题有关系 DroidPlugin的编译版本 比我的app版本高的多

**Comment by fuzhengchao** [comment]
@hiquanta 编译版本值compileSdkVersion吗，宿主和插件的不一致？

**Comment by hiquanta** [comment]
appCompat v7的问题 年前 工具都统一升级后 竟然好了 看包的错 应该 是v7包的兼容问题 尽量和 plugin的版本一致

**Comment by fuzhengchao** [comment]
@hiquanta 你们当时是必现问题还是偶现问题？

**Comment by hiquanta** [comment]
有些 手机上有  有些没有 发布是没一点问题  放到市场上问题大了

**Comment by fuzhengchao** [comment]
@hiquanta 1070082476 这是我qq，能加好友交流一下吗

**Comment by limengyun2008** [comment]
@hiquanta 这个问题我也碰到了。。。请问你都统一升级到哪个版本了呢？

**Comment by hiquanta** [comment]
和dp一样的版本吧，虽然android类库向下兼容，但为了保险，还是和dp一样吧
