### ISSUE TITLE
加载facebook时候，在registerStaticReceiver有很多提示找不到Recevier的异常

### ISSUE THREAD

**Issue by piersguo** [DroidPluginTeam/DroidPlugin#190]
在启动facebook应用时，在调用其callApplicationOnCreate中registerStaticReceiver，发现所有的Receiver都找不到，请问有人遇到过类似问题吗，如何解决的?

出错部分log如下:
2016-05-18 12:41:40.342 29233-10170/? E/PluginProcessManager registerStaticReceiver error=com.facebook.backgroundlocation.reporting.BackgroundLocationReportingBroadcastReceiver
java.lang.ClassNotFoundException: Didn't find class "com.facebook.backgroundlocation.reporting.BackgroundLocationReportingBroadcastReceiver" on path: DexPathList[[zip file "/data/data/com.test.example/Plugin/com.facebook.katana/apk/base-1.apk"],nativeLibraryDirectories=[/data/data/com.test.example/Plugin/com.facebook.katana/lib, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at com.morgoo.droidplugin.core.PluginClassLoader.loadClass(PluginClassLoader.java:102)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at com.morgoo.droidplugin.core.PluginProcessManager.registerStaticReceiver(PluginProcessManager.java:295)
	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callApplicationOnCreate(PluginInstrumentation.java:286)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:582)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:216)
	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:248)
	at com.morgoo.droidplugin.core.PluginProcessManager.preMakeApplication(PluginProcessManager.java:274)
	at com.morgoo.droidplugin.core.PluginProcessManager.preLoadApk(PluginProcessManager.java:230)
	at com.morgoo.droidplugin.hook.handle.PluginCallback.handleLaunchActivity(PluginCallback.java:377)
	at com.morgoo.droidplugin.hook.handle.PluginCallback.handleMessage(PluginCallback.java:245)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5663)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.facebook.backgroundlocation.reporting.BackgroundLocationReportingBroadcastReceiver" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 20 more
		Suppressed: java.lang.ClassNotFoundException: com.facebook.backgroundlocation.reporting.BackgroundLocationReportingBroadcastReceiver
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 21 more
		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

这种找不到Reciver错误有很多，限于太多，就贴一个供分析。

**Comment by colordancer** [comment]
同问

**Comment by piersguo** [comment]
我反编译了下facebook apk, 发现发编译后的jar包里面缺少了很多文件，对比其AndroidManifest.xml中，发现很多Service、Receiver文件都不在jar包里面，奇怪，这个是放哪里了，难道放lib so库文件里面了?

**Comment by asLody** [comment]
这些广播本来就是不存在的，系统允许你申明广播，但是类却不存在。FB显然是申明了但是类不存在。这些广播无视就可以了。

**Comment by 247321453** [comment]
exported=true时候，系统会先加载组件的类。

**Comment by piersguo** [comment]
多谢，那我再试试
