### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by pandaApe** [DroidPluginTeam/DroidPlugin#193]
在API19上并没有出现这样的问题。

buildToolsVersion = "23.0.2"
    compileSdkVersion = 23
    minSdkVersion = 14
    targetSdkVersion = 23

:PluginP08 A/MobUncaughtExceptionHandler: Unable to start activity ComponentInfo{com.codetroopers.betterpickersapp/com.codetroopers.betterpickers.sample.ListSamples}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codetroopers.betterpickersapp/com.codetroopers.betterpickers.sample.ListSamples}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                           Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                              at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                              at com.codetroopers.betterpickers.sample.ListSamples.onCreate(ListSamples.java:32)
                                                                              at android.app.Activity.performCreate(Activity.java:5990)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                              at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:110)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by hlllmr1314** [comment]
me too！

**Comment by hlllmr1314** [comment]
好不容易不报错了，我程序删除掉 再重新运行它又开始报错了！

**Comment by hlllmr1314** [comment]
兄弟 我也说不清楚了，我用命令安装到平板上运行是好的。祝你好运！

**Comment by pandaApe** [comment]
你看看 平板是哪个系统的？@hlllmr1314

**Comment by hlllmr1314** [comment]
@pandaApe
 samsung Galaxy Tab A
型号：p350  
Android版本：5.0.2

**Comment by lwcye** [comment]
我也碰到这个问题，到现在还没解决吗？
