### ISSUE TITLE
Youtube not working

### ISSUE THREAD

**Issue by FD-** [DroidPluginTeam/DroidPlugin#200]
I cannot get Youtube to work as a plugin. For installation, I had to disable the permission checks, but I don't think that's what caused the issues.

When I start the plugin, I always get this exception:

E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.SecurityException: Unknown calling package name 'com.google.android.youtube'.
at android.os.Parcel.readException(Parcel.java:1425)
at android.os.Parcel.readException(Parcel.java:1379)
at ecb.a(Unknown Source)
at ebe.a(Unknown Source)
at ebk.a(Unknown Source)
at ebm.a(Unknown Source)
at ebf.a(Unknown Source)
at ebh.c(Unknown Source)
at ebg.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4947)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
at dalvik.system.NativeStart.main(Native Method)

Does anyone have an idea where that exception comes from?

**Comment by cmzy** [comment]
It seem AppOps not be hooked..AppOps will check calling uid and packageName.You can hook the function "ecb.a" and change the Youtube's PackageName to host apk

**Comment by FD-** [comment]
The exception was actually thrown on Android 4.1, which to my knowledge did not yet have IAppOpsService. Does anyone else check uid and packageName?

How can I hook an arbitrary function like "ecb.a"?
