### ISSUE TITLE
 java.lang.SecurityException: Given caller package 

### ISSUE THREAD

**Issue by Morise** [DroidPluginTeam/DroidPlugin#212]
Product Model: SM-N9008
Sdk Version: 18, Version in string: 4.3
Debug:false
PName:system
imei:ad023ae2c1b08dc1af22c1bc0c26baa3
memory:1005940/-1695456
memoryClass:128

----------------------------------Exception---------------------------------------

----------------------------Exception message:Binary XML file line #7: Error inflating class com.example.safewebview.SafeWebView

----------------------------Exception StackTrace:
android.view.InflateException: Binary XML file line #7: Error inflating class com.example.safewebview.SafeWebView
    at android.view.LayoutInflater.createView(LayoutInflater.java:626)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
    at android.view.View.inflate(View.java:17860)
    at com.example.deskgameunion.activity.a.a.G(SourceFile:134)
    at com.example.deskgameunion.activity.base.fragment.b.a(SourceFile:51)
    at com.example.deskgameunion.activity.base.fragment.c.a(SourceFile:28)
    at android.support.v4.app.Fragment.b(SourceFile:1460)
    at android.support.v4.app.m.a(SourceFile:911)
    at android.support.v4.app.m.a(SourceFile:1088)
    at android.support.v4.app.a.run(SourceFile:682)
    at android.support.v4.app.m.d(SourceFile:1444)
    at android.support.v4.app.m.b(SourceFile:461)
    at android.support.v4.app.q.a(SourceFile:141)
    at android.support.v4.view.ViewPager.a(SourceFile:1011)
    at android.support.v4.view.ViewPager.b(SourceFile:880)
    at android.support.v4.view.ViewPager.onMeasure(SourceFile:1374)
    at android.view.View.measure(View.java:16829)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
    at android.view.View.measure(View.java:16829)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:16829)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:16829)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    at android.view.View.measure(View.java:16829)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2581)
    at android.view.View.measure(View.java:16829)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2186)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1349)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1532)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6339)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
    at android.view.Choreographer.doCallbacks(Choreographer.java:591)
    at android.view.Choreographer.doFrame(Choreographer.java:561)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
    at android.os.Handler.handleCallback(Handler.java:730)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5450)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
    at android.view.LayoutInflater.createView(LayoutInflater.java:600)
    ... 54 more
Caused by: java.lang.SecurityException: Given caller package com.example.ggift is not running in process ProcessRecord{4358f040 12355:com.example.gameunion:PluginP07/u0a10197}
    at android.os.Parcel.readException(Parcel.java:1431)
    at android.os.Parcel.readException(Parcel.java:1385)
    at android.app.ActivityManagerProxy.registerReceiver(ActivityManagerNative.java:2466)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1717)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1685)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1679)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:453)
    at android.webkit.WebViewClassic.setupPackageListener(WebViewClassic.java:3483)
    at android.webkit.WebViewClassic.init(WebViewClassic.java:2939)
    at android.webkit.WebView.<init>(WebView.java:534)
    at android.webkit.WebView.<init>(WebView.java:500)
    at android.webkit.WebView.<init>(WebView.java:481)
    at android.webkit.WebView.<init>(WebView.java:470)
    at com.example.safewebview.SafeWebView.<init>(SourceFile:40)
#     ... 57 more

集成插件后遇到了这种异常Caused by: java.lang.SecurityException: Given caller package 不知道有没有人遇到过

**Comment by cmzy** [comment]
这个最新的代码应该没问题啊

**Comment by Morise** [comment]
这个找到原因了 是宿主加固后产生的
