### ISSUE TITLE
在插件里面使用了umeng的统计SDK，无法进行统计

### ISSUE THREAD

**Issue by leleliu008** [DroidPluginTeam/DroidPlugin#227]
在插件里面使用了umeng的统计SDK，无法进行统计，请问是什么原因？

**Comment by leleliu008** [comment]
E/SQLiteDatabase(11756): Failed to open database '/data/data/com.umeng.example/databases/cc/cc.db'.
E/SQLiteDatabase(11756): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:717)
E/SQLiteDatabase(11756): 	at u.aly.e.openOrCreateDatabase(UMCCPathDatabaseContext.java:44)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
E/SQLiteDatabase(11756): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
E/SQLiteDatabase(11756): 	at u.aly.b.b(DatabaseManager.java:49)
E/SQLiteDatabase(11756): 	at u.aly.o.a(UMCCStorageManager.java:145)
E/SQLiteDatabase(11756): 	at u.aly.m.d(UMCCAggregatedManager.java:371)
E/SQLiteDatabase(11756): 	at com.umeng.analytics.h.h(StoreHelper.java:261)
E/SQLiteDatabase(11756): 	at u.aly.ad.a(CacheImpl.java:241)
E/SQLiteDatabase(11756): 	at u.aly.ad.f(CacheImpl.java:274)
E/SQLiteDatabase(11756): 	at u.aly.ad.a(CacheImpl.java:142)
E/SQLiteDatabase(11756): 	at u.aly.ad.a(CacheImpl.java:101)
E/SQLiteDatabase(11756): 	at u.aly.ae$1.a(CacheService.java:41)
E/SQLiteDatabase(11756): 	at com.umeng.analytics.g.run(SafeRunnable.java:8)
E/SQLiteDatabase(11756): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/SQLiteDatabase(11756): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/SQLiteDatabase(11756): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
E/SQLiteDatabase(11756): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
E/SQLiteDatabase(11756): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SQLiteDatabase(11756): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SQLiteDatabase(11756): 	at java.lang.Thread.run(Thread.java:841)
E/MobclickAgent(11756): notifyUploadSuccess error
W/System.err(11756): java.lang.NullPointerException
W/System.err(11756): 	at u.aly.b.c(DatabaseManager.java:57)
W/System.err(11756): 	at u.aly.o.a(UMCCStorageManager.java:150)
W/System.err(11756): 	at u.aly.m.d(UMCCAggregatedManager.java:371)
W/System.err(11756): 	at com.umeng.analytics.h.h(StoreHelper.java:261)
W/System.err(11756): 	at u.aly.ad.a(CacheImpl.java:241)
W/System.err(11756): 	at u.aly.ad.f(CacheImpl.java:274)
W/System.err(11756): 	at u.aly.ad.a(CacheImpl.java:142)
W/System.err(11756): 	at u.aly.ad.a(CacheImpl.java:101)
W/System.err(11756): 	at u.aly.ae$1.a(CacheService.java:41)
W/System.err(11756): 	at com.umeng.analytics.g.run(SafeRunnable.java:8)
W/System.err(11756): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err(11756): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(11756): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
W/System.err(11756): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
W/System.err(11756): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(11756): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(11756): 	at java.lang.Thread.run(Thread.java:841)
I/ActivityManager(  591): Displayed com.example.TestPlugin/com.morgoo.droidplugin.stub.ActivityStub$P02$Standard00: +583ms


/data/data/com.umeng.example/是插件的私有目录，但是以插件方式运行，这个目录并不存在，该如何访问？或者可否在插件里得到Host的AppContext？这样就不用插件的package了，避免出现此问题。

**Comment by 247321453** [comment]
貌似是sqlite没有hook住

**Comment by leleliu008** [comment]
有办法解决吗？增加一个Hook类？

**Comment by lordrings104** [comment]
暂时使用旧版本的， 例如5.6.4

**Comment by banketree** [comment]
读写权限问题

**Comment by cqllang** [comment]
无法防止第三方应用使用最新版本友盟啊。。。
