### ISSUE TITLE
求助：加载微信能运行，能发消息，但收不到，进入摇一摇界面就立刻受到消息。

### ISSUE THREAD

**Issue by bhui** [DroidPluginTeam/DroidPlugin#233]
机型：华为荣耀 H30-L02 5.1.1

**Comment by Howie-hxu** [comment]
目前我调试的结果跟你类似，似乎微信主界面需要resume一下才可以收到消息，原因未知

**Comment by bhui** [comment]
@Howie-hxu  dumpsys acitivity services看插件的service不存在。很有可能是这里不成功导致的。
不知道你那边情况是否一样？

**Comment by bhui** [comment]
@Howie-hxu  反编译看了金山开小号，有专门处理com.tencent.mm.booter.NotifyReceiver的代码

**Comment by Eaoll** [comment]
@bhui 刚刚看了下金山开小号，应该是在droidplugin基础上做的吧

**Comment by liuchenx** [comment]
为什么我开微信停在月球界面?

**Comment by D-Red** [comment]
@Howie-hxu 我运行Demo也是一样，停留在微信月求界面，请问你解决了吗

**Comment by huyangdelin** [comment]
我和楼主遇到相同问题，请问楼主解决了吗 ？

**Comment by huyangdelin** [comment]
有可能是如下异常，导致om.tencent.mm.booter.CoreService 起不来，导致收不到消息，目前不知道有解没有 ？
09-22 13:15:04.532: E/AbstractServiceStub(7200): handleExceptionjava.lang.reflect.InvocationTargetException
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.morgoo.droidplugin.stub.ServcesManager.handleCreateServiceOne(ServcesManager.java:134)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.morgoo.droidplugin.stub.ServcesManager.onBind(ServcesManager.java:273)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.morgoo.droidplugin.stub.AbstractServiceStub.onBind(AbstractServiceStub.java:139)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.handleBindService(ActivityThread.java:2948)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.access$2000(ActivityThread.java:168)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.os.Looper.loop(Looper.java:150)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.main(ActivityThread.java:5643)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
09-22 13:15:04.532: E/AbstractServiceStub(7200): Caused by: java.lang.RuntimeException: Unable to create service com.tencent.mm.booter.CoreService: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tencent.mm.network.y.reset()' on a null object reference
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2931)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	... 13 more
09-22 13:15:04.532: E/AbstractServiceStub(7200): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tencent.mm.network.y.reset()' on a null object reference
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.tencent.mm.network.r.a(SourceFile:53)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.tencent.mm.network.r$5.run(SourceFile:270)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.tencent.mm.sdk.platformtools.az.b(SourceFile:78)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.tencent.mm.network.r.reset(SourceFile:274)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at com.tencent.mm.booter.CoreService.onCreate(SourceFile:159)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2918)
09-22 13:15:04.532: E/AbstractServiceStub(7200): 	... 13 more
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): invokeMethod connectedjava.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.toString()' on a null object reference
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at com.morgoo.droidplugin.reflect.MethodUtils.getKey(MethodUtils.java:46)
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at com.morgoo.droidplugin.reflect.MethodUtils.getMatchingAccessibleMethod(MethodUtils.java:155)
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:207)
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:246)
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1.connected(IActivityManagerHookHandle.java:1079)
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:58)
09-22 13:15:04.535: E/IActivityManagerHookHandle(6947): 	at android.os.Binder.execTransact(Binder.java:453)
09-22 13:15:04.569: E/AbstractServiceStub(7200): handleExceptionjava.lang.reflect.InvocationTargetException
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.morgoo.droidplugin.stub.ServcesManager.handleCreateServiceOne(ServcesManager.java:134)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.morgoo.droidplugin.stub.ServcesManager.onStart(ServcesManager.java:247)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.morgoo.droidplugin.stub.AbstractServiceStub.onStart(AbstractServiceStub.java:86)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.Service.onStartCommand(Service.java:459)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3060)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.access$2200(ActivityThread.java:168)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.os.Looper.loop(Looper.java:150)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.main(ActivityThread.java:5643)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at java.lang.reflect.Method.invoke(Native Method)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
09-22 13:15:04.569: E/AbstractServiceStub(7200): Caused by: java.lang.RuntimeException: Unable to create service com.tencent.mm.booter.CoreService: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tencent.mm.network.y.reset()' on a null object reference
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2931)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	... 14 more
09-22 13:15:04.569: E/AbstractServiceStub(7200): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tencent.mm.network.y.reset()' on a null object reference
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.tencent.mm.network.r.a(SourceFile:53)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.tencent.mm.network.r$5.run(SourceFile:270)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.tencent.mm.sdk.platformtools.az.b(SourceFile:78)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.tencent.mm.network.r.reset(SourceFile:274)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at com.tencent.mm.booter.CoreService.onCreate(SourceFile:159)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2918)
09-22 13:15:04.569: E/AbstractServiceStub(7200): 	... 14 more

**Comment by Cornflower1991** [comment]
我用微信怎么不能启动 求解

**Comment by the-sparrow** [comment]
我也困扰于此问题，每次从另一个手机微信号向此运行的微信号发消息，tcpdump 看到有数据来，但就是没消息提示，各位大神解决后麻烦指点迷津！

**Comment by scarerow** [comment]
请问楼主，你的微信版本是多少

**Comment by scarerow** [comment]
@the-sparrow 我用6.20版本的微信不能登录，请问你用的微信是什么版本。

**Comment by ZhangPeibin** [comment]
请问各位是做开微信的吗!
