### ISSUE TITLE
混淆之后bind插件中的service会报IllegalArgumentException，混淆之前没问题

### ISSUE THREAD

**Issue by xingjiyuan** [DroidPluginTeam/DroidPlugin#239]
java.lang.IllegalArgumentException: argument 5 should have type android.app.IServiceConnection, got com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:52)
                                                     at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(ProxyHook.java:60)
                                                     at com.morgoo.droidplugin.hook.proxy.IActivityManagerHook.invoke(IActivityManagerHook.java:63)
                                                     at $Proxy17.bindService(Native Method)
                                                     at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1656)
                                                     at android.app.ContextImpl.bindService(ContextImpl.java:1625)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:517)

混淆配置如下：
-dontwarn com.morgoo.**
-keep class com.morgoo.** { *;}
-keep class android.util.Singleton{*;}
-keep class android.app.ILicensingService{*;}

**Comment by xingjiyuan** [comment]
修改了混淆配置，问题解决：
-dontwarn com.morgoo.**
-keep class com.morgoo.** { *;}
-keep class android.util.Singleton{*;}
-keep class android.app.IServiceConnection{*;}
