### ISSUE TITLE
4.4的手机安装成功，5.0以上的一直卡在安装中ing

### ISSUE THREAD

**Issue by 70kg** [DroidPluginTeam/DroidPlugin#248]
```
 android.os.RemoteException
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.parser.PackageParserApi21.collectCertificates(PackageParserApi21.java:116)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.parser.PluginPackageParser.collectCertificates(PluginPackageParser.java:232)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.IPluginManagerImpl.installPackage(IPluginManagerImpl.java:879)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.PluginManager.installPackage(PluginManager.java:855)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.example.TestPlugin.ApkFragment.doInstall(ApkFragment.java:290)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.example.TestPlugin.ApkFragment.access$100(ApkFragment.java:37)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at com.example.TestPlugin.ApkFragment$5.run(ApkFragment.java:261)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err: Caused by: java.lang.reflect.InvocationTargetException
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err: 	... 9 more
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err: Caused by: android.content.pm.PackageParser$PackageParserException: Failed to collect certificates from /data/data/com.example.TestPlugin/Plugin/com.example.myapplication/apk/base-1.apk
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1154)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err:     at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1079)
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err: 	... 9 more
07-27 16:29:24.466 4480-4550/com.example.TestPlugin W/System.err: Caused by: java.lang.NullPointerException: Attempt to get length of null array
07-27 16:29:24.473 4480-4550/com.example.TestPlugin W/System.err:     at java.util.jar.Manifest.read(Manifest.java:187)
07-27 16:29:24.473 4480-4550/com.example.TestPlugin W/System.err:     at java.util.jar.Manifest.<init>(Manifest.java:106)
07-27 16:29:24.473 4480-4550/com.example.TestPlugin W/System.err:     at java.util.jar.StrictJarFile.<init>(StrictJarFile.java:65)
07-27 16:29:24.473 4480-4550/com.example.TestPlugin W/System.err:     at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1095)
07-27 16:29:24.473 4480-4550/com.example.TestPlugin W/System.err: 	... 10 more
```

**Comment by 70kg** [comment]
貌似一定要签名过。。
