### ISSUE TITLE
SQLiteDatabase﹕ Failed to open database '/data/data/com.baidu.push.example/database/pushinfo.db'.

### ISSUE THREAD

**Issue by MrHuangXin** [DroidPluginTeam/DroidPlugin#256]
08-07 14:36:24.424    5084-5084/com.example.TestPlugin:PluginP02 E/SQLiteLog﹕ (14) cannot open file at line 30197 of [000197cc4e]
08-07 14:36:24.424    5084-5084/com.example.TestPlugin:PluginP02 E/SQLiteLog﹕ (14) os_unix.c:30197: (13) open(/data/data/com.baidu.push.example/database/pushinfo.db) -
08-07 14:36:24.429    5084-5084/com.example.TestPlugin:PluginP02 E/SQLiteDatabase﹕ Failed to open database '/data/data/com.baidu.push.example/database/pushinfo.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1009)
            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at com.baidu.android.pushservice.util.s.a(Unknown Source)
            at com.baidu.android.pushservice.PushInfoProvider.query(Unknown Source)
            at android.content.ContentProvider.query(ContentProvider.java:857)
            at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
            at android.content.ContentResolver.query(ContentResolver.java:471)
            at android.content.ContentResolver.query(ContentResolver.java:407)
            at com.baidu.android.pushservice.util.t.b(Unknown Source)
            at com.baidu.android.pushservice.util.v.u(Unknown Source)
            at com.baidu.android.pushservice.util.u.d(Unknown Source)
            at com.baidu.android.pushservice.util.v.a(Unknown Source)
            at com.baidu.android.pushservice.PushManager.startWork(Unknown Source)
            at com.baidu.android.pushservice.PushManager.startWork(Unknown Source)
            at com.baidu.push.example.PushDemoActivity.onCreate(PushDemoActivity.java:125)
            at android.app.Activity.performCreate(Activity.java:5285)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
            at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:110)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
            at android.app.ActivityThread.access$1100(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5314)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
            at dalvik.system.NativeStart.main(Native Method)
![qq 20160807145323](https://cloud.githubusercontent.com/assets/15179354/17460958/f571ff9c-5cad-11e6-8545-38fca78d5dc5.png)

**Comment by MrHuangXin** [comment]
@asLody
