### ISSUE TITLE
Caused by: java.lang.RuntimeException: Package not found: com.android.webview

### ISSUE THREAD

**Issue by wqqgt** [DroidPluginTeam/DroidPlugin#260]
在使用的过程中，启动崩溃，堆栈如下
08-08 14:46:39.842 W/System.err( 7415): Caused by: java.lang.RuntimeException: Package not found: com.android.webview
08-08 14:46:39.842 W/System.err( 7415): at android.webkit.WebViewDelegate.getPackageId(WebViewDelegate.java:138)
08-08 14:46:39.842 W/System.err( 7415): at com.android.webview.chromium.WebViewDelegateFactory$ProxyDelegate.getPackageId(WebViewDelegateFactory.java:153)
08-08 14:46:39.842 W/System.err( 7415): at com.android.webview.chromium.WebViewChromiumFactoryProvider.setUpResources(WebViewChromiumFactoryProvider.java:330)
08-08 14:46:39.842 W/System.err( 7415): at com.android.webview.chromium.WebViewChromiumFactoryProvider.startChromiumLocked(WebViewChromiumFactoryProvider.java:248)
08-08 14:46:39.842 W/System.err( 7415): at com.android.webview.chromium.WebViewChromiumFactoryProvider.ensureChromiumStartedLocked(WebViewChromiumFactoryProvider.java:195)
08-08 14:46:39.842 W/System.err( 7415): at com.android.webview.chromium.WebViewChromiumFactoryProvider.startYourEngines(WebViewChromiumFactoryProvider.java:289)
08-08 14:46:39.842 W/System.err( 7415): at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:249)

**Comment by wqqgt** [comment]
在乐视的手机上，有人遇到过吗？

**Comment by jordanqin** [comment]
这个问题你解决了吗？我的友盟后台出现了此异常，求教，万分感谢。

**Comment by TomasYu** [comment]
Process: com.chaozh.iReaderFree, PID: 18120
    java.lang.RuntimeException: Package not found: com.android.webview
        at android.webkit.WebViewDelegate.getPackageId(WebViewDelegate.java:163)
        at com.android.webview.chromium.WebViewDelegateFactory$ProxyDelegate.getPackageId(WebViewDelegateFactory.java:165)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.setUpResources(WebViewChromiumFactoryProvider.java:388)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.startChromiumLocked(WebViewChromiumFactoryProvider.java:305)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.ensureChromiumStartedLocked(WebViewChromiumFactoryProvider.java:252)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.startYourEngines(WebViewChromiumFactoryProvider.java:347)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:238)
        at android.webkit.WebView.<init>(WebView.java:636)
        at android.webkit.WebView.<init>(WebView.java:572)
        at android.webkit.WebView.<init>(WebView.java:555)
