### ISSUE TITLE
【兼容性问题】nexus 6P 加载插件失败

### ISSUE THREAD

**Issue by SheepYoung** [DroidPluginTeam/DroidPlugin#261]
环境是6.01 机器： nexus 6p ，看上去好像是以为加载的class与主程序的class重复了，存在两份相同包名的class，怀疑是不是6.0.x 进程class的时候，回去检查主apk的class？ 
log 如下： 
08-24 11:22:50.001 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: #++++++++++Record By Bugly++++++++++#
08-24 11:22:50.001 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # You can use Bugly(http:\bugly.qq.com) to get more Crash Detail!
08-24 11:22:50.001 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # PKG NAME: com.microvideo.mivi
08-24 11:22:50.001 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # APP VER: 1.0.7.8
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # LAUNCH TIME: 2016-08-24 11:22:49
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # CRASH TYPE: JAVA_CRASH
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # CRASH TIME: 2016-08-24 11:22:50
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # CRASH PROCESS: com.microvideo.mivi:PluginP03
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # CRASH THREAD: main
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # REPORT ID: 0d083612-443e-47c0-a273-c427699db3da
08-24 11:22:50.002 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # CRASH DEVICE: Nexus 6P ROOTED
08-24 11:22:50.003 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # RUNTIME AVAIL RAM:1387192320 ROM:23309619200 SD:23309619200
08-24 11:22:50.003 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # RUNTIME TOTAL RAM:2833899520 ROM:26854621184 SD:26854621184
08-24 11:22:50.003 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: # CRASH STACK: 
08-24 11:22:50.003 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: **java.lang.IncompatibleClassChangeError: Structural change of com.framwork.activity.BaseActivity is hazardous** (/data/user/0/com.microvideo.mivi/Plugin/com.yimu.holiday/dalvik-cache/base-1.dex at compile time, /data/user/0/com.microvideo.mivi/cache/slice-slice_9-classes.dex at runtime): Virtual method count off: 11 vs 17
                                                                            Lcom/framwork/activity/BaseActivity; (Compile time):
                                                                             Static fields:
                                                                             Instance fields:
                                                                              Lcom/framwork/activity/ViewBusinessBinder; mViewBusinessBander
                                                                              Landroid/app/ProgressDialog; pd
                                                                             Direct methods:
                                                                              <init>()V
                                                                             Virtual methods:
                                                                              back(Landroid/view/View;)V
                                                                              block(Ljava/lang/String;Z)V
                                                                              confirm(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Runnable;)V
                                                                              confirm(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Runnable;Ljava/lang/Runnable;)V
                                                                              finishSelfDelay()V
                                                                              getUiClassName()Ljava/lang/String;
                                                                              onBindBusinessInterface(Lcom/framwork/activity/ViewBusinessBinder;)V
                                                                              onCreate(Landroid/os/Bundle;)V
                                                                              onCreate(Landroid/os/Bundle;Landroid/os/PersistableBundle;)V
                                                                              onDestroy()V
                                                                              unblock()V
                                                                            Lcom/framwork/activity/BaseActivity; (Runtime):
                                                                             Static fields:
                                                                              Lcom/android/tools/fd/runtime/IncrementalChange; $change
                                                                             Instance fields:
                                                                              Z isInvokeByPlugin
                                                                              Landroid/app/AlertDialog; mAlertDialog
                                                                              Lcom/framwork/activity/ViewBusinessBinder; mViewBusinessBander
                                                                              Landroid/app/ProgressDialog; pd
                                                                             Direct methods:
                                                                              <init>()V
                                                                              <init>([Ljava/lang/Object;Lcom/android/tools/fd/runtime/InstantReloadException;)V
                                                                              access$super(Lcom/framwork/activity/BaseActivity;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
                                                                             Virtual methods:
                                                                              back(Landroid/view/View;)V
                                                                              block(Ljava/lang/String;Z)V
                                                                              cancelAlertDialog()V
                                                                              confirm(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Runnable;)V
                                                                              confirm(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Runnable;Ljava/lang/Runnable;)V
                                                                              finishSelfDelay()V
                                                                              finishSelfDelayFast()V
                                                                              getUiClassName()Ljava/lang/String;
                                                                              isAlertDialogShowing()Z
                                                                              onBindBusinessInterface(Lcom/framwork/activity/ViewBusinessBinder;)V
                                                                              onCreate(Landroid/os/Bundle;)V
                                                                              onCreate(Landroid/os/Bundle;Landroid/os/PersistableBundle;)V
                                                                              onDestroy()V
                                                                              onKeyDown(ILandroid/view/KeyEvent;)Z
                                                                              onPreFinish()V
                                                                              onResume()V
                                                                              unblock()V
                                                                             (declaration of 'com.yimu.main.MainActivity' appears in /data/user/0/com.microvideo.mivi/Plugin/com.yimu.holiday/apk/base-1.apk)
                                                                                at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                                at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                                at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                                at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                at com.morgoo.droidplugin.core.PluginClassLoader.loadClass(PluginClassLoader.java:74)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-24 11:22:50.003 15472-15472/com.microvideo.mivi:PluginP03 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
08-24 11:23:01.091 15712-15712/com.microvideo.mivi:ServiceDemon E/CrashReport: --------------------------------------------------------------------------------------------
08-24 11:23:01.091 15712-15712/com.microvideo.mivi:ServiceDemon E/CrashReport: --------------------------------------------------------------------------------------------
08-24 11:23:01.377 15712-15712/com.microvideo.mivi:ServiceDemon E/WatchDog: demon service on create...
08-24 11:23:27.858 17629-17629/com.microvideo.mivi E/WatchDog: receiver:service_demon_check_event
08-24 11:23:27.862 17629-17629/com.microvideo.mivi E/WatchDog: demon exist....

**Comment by SheepYoung** [comment]
我发现只有在debug的情况下才会出现，而宿主打包方式是release 没有该问题，我使用android 4.x是手机编译的debug包，好像也没有问题，不知道和ART 有关系。 @cmzy 
是不是classloader 一样导致的， 插件的加载使用了宿主的classloader？

**Comment by SheepYoung** [comment]
更新了编译器版本,问题竟然不存在了
