### ISSUE TITLE
插件安装成功，但是启动失败

### ISSUE THREAD

**Issue by LIHAIYI** [DroidPluginTeam/DroidPlugin#271]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.test.demo/com.test.demo.MainActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by LIHAIYI** [comment]
单独安装插件是OK的

**Comment by LIHAIYI** [comment]
: android.os.RemoteException
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.am.MyActivityManagerService.throwException(MyActivityManagerService.java:228)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.am.MyActivityManagerService.selectStubActivityInfo(MyActivityManagerService.java:379)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.IPluginManagerImpl.selectStubActivityInfo(IPluginManagerImpl.java:1222)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.IPluginManagerImpl.selectStubActivityInfoByIntent(IPluginManagerImpl.java:1238)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.pm.PluginManager.selectStubActivityInfo(PluginManager.java:660)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle.selectProxyActivity(IActivityManagerHookHandle.java:2099)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle.access$300(IActivityManagerHookHandle.java:80)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$startActivity.doReplaceIntentForStartActivityAPIHigh(IActivityManagerHookHandle.java:171)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$startActivity.beforeInvoke(IActivityManagerHookHandle.java:291)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:48)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(ProxyHook.java:60)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.hook.proxy.IActivityManagerHook.invoke(IActivityManagerHook.java:63)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:397)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at $Proxy14.startActivity(Unknown Source)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1480)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3744)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3705)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:849)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.support.v4.app.Fragment.startActivity(Fragment.java:916)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:51)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:147)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.view.View.performClick(View.java:4759)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.view.View$PerformClick.run(View.java:19770)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5235)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err: Caused by: java.lang.RuntimeException: 没有可用的进程了
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err:     at com.morgoo.droidplugin.am.MyActivityManagerService.throwException(MyActivityManagerService.java:229)
09-22 14:59:17.158 4211-4211/com.example.TestPlugin W/System.err: 	... 31 more

**Comment by LIHAIYI** [comment]
@cmzy @htynkn @markzhai @JackCho @tiann

**Comment by boyrt** [comment]
我也遇到你一样的问题，临时解决方案是将DroidPlugin清单文件中的9个坑进程删掉了5个，然后启动了插件apk
