### ISSUE TITLE
支付宝无法调起

### ISSUE THREAD

**Issue by cxzadmini** [DroidPluginTeam/DroidPlugin#279]
10-19 21:20:08.581 1160-2806/system_process W/PackageManager: checkUidPermission(): android.permission.WRITE_SECURE_SETTINGS of 10124 is denied.
10-19 21:20:08.581 1160-2806/system_process W/AppOps: Bad call: specified package com.eval.line under uid 10124 but it is really -1
10-19 21:20:08.581 1160-2806/system_process E/DatabaseUtils: Writing exception to parcel
                                                             java.lang.SecurityException: Package com.eval.line does not belong to 10124
                                                                 at android.app.AppOpsManager.checkPackage(AppOpsManager.java:1563)
                                                                 at android.content.ContentProvider.getCallingPackage(ContentProvider.java:824)
                                                                 at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:902)
                                                                 at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:876)
                                                                 at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:259)
                                                                 at android.content.ContentProvider$Transport.call(ContentProvider.java:434)
                                                                 at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
                                                                 at android.os.Binder.execTransact(Binder.java:461)
10-19 21:20:08.582 1160-2632/system_process D/AudioTrack: AudioTrackThread::pause

AppOpsManager所有方法都已经hook了，无法调用支付宝支付页面

现象：还原出厂设置后，安装插件，调用支付宝支付，无法调起

仔细查看是因为宿主加 了     <uses-permission android:name="android.permission.WRITE_SETTINGS"/> 权限，若是宿主没有加这个权限，就不会出现上述问题，不知道是什么原因，有大神解答一下不?

**Comment by cxzadmini** [comment]
宿主 加了 android.permission.WRITE_SETTINGS权限，若是宿主没有加这个权限，就不会出现上述问题

**Comment by cxzadmini** [comment]
部分服务没有hook。非框架问题

**Comment by cxzadmini** [comment]
已解决

**Comment by zhaoqingpu** [comment]
@cxzadmini 您好，最后怎么解决的能唤起微信和支付宝进行支付吗？
