### ISSUE TITLE
droidplugin.core.PluginClassLoader cannot be cast to dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by cxzadmini** [DroidPluginTeam/DroidPlugin#290]
12-04 14:07:42.488 8845-8845/? W/System.err: java.lang.ClassCastException: cn.nineox.droidplugin.core.PluginClassLoader cannot be cast to dalvik.system.PathClassLoader
12-04 14:07:42.488 8845-8845/? W/System.err:     at com.autohome.framework.tools.DexUtils.getPathClassLoader(DexUtils.java:87)
12-04 14:07:42.488 8845-8845/? W/System.err:     at com.autohome.framework.tools.DexUtils.injectDex(DexUtils.java:27)
12-04 14:07:42.488 8845-8845/? W/System.err:     at com.autohome.framework.tools.DexUtils.injectDexAtFirst(DexUtils.java:17)
12-04 14:07:42.488 8845-8845/? W/System.err:     at com.autohome.framework.core.HotFix.loadPatch(HotFix.java:49)
12-04 14:07:42.488 8845-8845/? W/System.err:     at com.autohome.framework.core.HotFix.init(HotFix.java:33)
12-04 14:07:42.489 8845-8845/? W/System.err:     at com.cubic.autohome.hotfix.HotFixManager.init(HotFixManager.java:48)
12-04 14:07:42.489 8845-8845/? W/System.err:     at com.cubic.autohome.MyApplication.attachBaseContext(MyApplication.java:147)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.app.Application.attach(Application.java:198)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:993)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:602)
12-04 14:07:42.489 8845-8845/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-04 14:07:42.489 8845-8845/? W/System.err:     at cn.nineox.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:214)
12-04 14:07:42.489 8845-8845/? W/System.err:     at cn.nineox.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:246)
12-04 14:07:42.489 8845-8845/? W/System.err:     at cn.nineox.droidplugin.core.PluginProcessManager.preMakeApplication(PluginProcessManager.java:272)
12-04 14:07:42.489 8845-8845/? W/System.err:     at cn.nineox.droidplugin.core.PluginProcessManager.preLoadApk(PluginProcessManager.java:228)
12-04 14:07:42.489 8845-8845/? W/System.err:     at cn.nineox.droidplugin.hook.handle.PluginCallback.handleLaunchActivity(PluginCallback.java:377)
12-04 14:07:42.489 8845-8845/? W/System.err:     at cn.nineox.droidplugin.hook.handle.PluginCallback.handleMessage(PluginCallback.java:245)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.os.Looper.loop(Looper.java:207)
12-04 14:07:42.489 8845-8845/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5955)
12-04 14:07:42.489 8845-8845/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-04 14:07:42.489 8845-8845/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
12-04 14:07:42.489 8845-8845/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
12-04 14:07:42.510 340-340/? E/SELinux: avc:  denied  { find } for service=batteryproperties scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:healthd_service:s0 tclass=service_manager
12-04 14:07:42.518 8845-8845/? E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
12-04 14:07:42.539 1096-1954/? W/PackageManager: checkUidPermission(): android.permission.INTERACT_ACROSS_USERS_FULL of 12067 is denied.
12-04 14:07:42.539 1096-1954/? W/PackageManager: checkUidPermission(): android.permission.REAL_GET_TASKS of 12067 is denied.
12-04 14:07:42.552 1096-1908/? W/PackageManager: checkUidPermission(): android.permission.INTERACT_ACROSS_USERS_FULL of 12067 is denied.
12-04 14:07:42.552 1096-1908/? W/PackageManager: checkUidPermission(): android.permission.REAL_GET_TASKS of 12067 is denied.
12-04 14:07:42.560 8845-8845/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: cn.nineox.mutilopenhelper:PluginP01, PID: 8845
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/autohome/hotfixhack/Hack;
                                                     at com.cubic.autohome.LogoActivity$6.<init>(LogoActivity.java:753)
                                                     at com.cubic.autohome.LogoActivity.<init>(LogoActivity.java:753)
                                                     at java.lang.Class.newInstance(Native Method)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2774)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588)
                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                     at android.os.Looper.loop(Looper.java:207)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5955)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.autohome.hotfixhack.Hack" on path: DexPathList[[zip file "/data/user/0/cn.nineox.mutilopenhelper/Plugin/com.cubic.autohome/apk/base-1.apk"],nativeLibraryDirectories=[/data/user/0/cn.nineox.mutilopenhelper/Plugin/com.cubic.autohome/lib, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at cn.nineox.droidplugin.core.PluginClassLoader.loadClass(PluginClassLoader.java:74)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.cubic.autohome.LogoActivity$6.<init>(LogoActivity.java:753) 
                                                     at com.cubic.autohome.LogoActivity.<init>(LogoActivity.java:753) 
                                                     at java.lang.Class.newInstance(Native Method) 
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1079) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2604) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2774) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                     at android.os.Looper.loop(Looper.java:207) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5955) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801) 
                                                 	Suppressed: java.lang.ClassNotFoundException: com.autohome.hotfixhack.Hack
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 16 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
12-04 14:07:42.562 1096-2038/? W/ActivityManager:   Force finishing activity cn.nineox.mutilopenhelper/cn.nineox.droidplugin.stub.ActivityStub$P01$Standard00

 加载部分使用hotfix的APP出现崩溃

**Comment by cmzy** [comment]
需要native io hook
