### ISSUE TITLE
需要适配某些ROM的BaiduAssetManager类

### ISSUE THREAD

**Issue by balizhuang2012** [DroidPluginTeam/DroidPlugin#293]
java.lang.ClassCastException: android.content.res.AssetManager cannot be cast to android.content.res.BaiduAssetManager
原因是若干rom没有AssetManager类，变成了BaiduAssetManager类（可能是刷rom了，因为线上发现若干不同厂商的手机都报了这个bug，例如有一台华为G610_T11）。麻烦适配一下吧

**Comment by cmzy** [comment]
能否给一个详细的crash log？

**Comment by balizhuang2012** [comment]
这是我们使用Tinker时遇上的崩溃，但是可想而知任何插件系统都需要做同样的适配。可以参考Tinker，他们在最新版本1.7.5已经适配了。

android.content.res.Resources$NotFoundException: File r/m/lg.xml from drawable resource ID #0x7f020550
	at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:160)
	at android.content.res.BaiduResources.loadDrawable(BaiduResources.java:103)
	at android.content.res.Resources.getDrawable(Resources.java:673)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2847)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2890)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1583)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2978)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.access$600(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1346)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5320)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by balizhuang2012** [comment]
之前贴错了，这里是完整的堆栈，关键在于caused by的部分。
android.content.res.Resources$NotFoundException: File r/m/lg.xml from drawable resource ID #0x7f020550
	at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:160)
	at android.content.res.BaiduResources.loadDrawable(BaiduResources.java:103)
	at android.content.res.Resources.getDrawable(Resources.java:673)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2847)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2890)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1583)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2978)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.access$600(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1346)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5320)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File r/c/ow.png from drawable resource ID #0x7f0202a4
	at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:180)
	at android.content.res.BaiduResources.loadDrawable(BaiduResources.java:103)
	at android.content.res.Resources.getDrawable(Resources.java:673)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:156)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
	at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:157)
	... 17 more
Caused by: java.lang.ClassCastException: android.content.res.AssetManager cannot be cast to android.content.res.BaiduAssetManager
	at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:168)
	... 23 more

**Comment by cmzy** [comment]
是插件在宿主中运行的时候会报这个错？插件直接运行会报这个错么？
在droidplugin中，并没有涉及到AssetManager的代码啊。

**Comment by balizhuang2012** [comment]
不好意思，我想当然了，原来droidplugin的资源替换实现不是通过AssetManager做的。给您添麻烦了
