### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [DroidPluginTeam/DroidPlugin#300]
When using DroidPlugin with a google drive integrated Sample app I get the following issue. Any help would be appreciated.

 E/MyCrashHandler(29642): uncaughtExceptionjava.lang.RuntimeException: Unable to resume activity {com.example.quickstart/com.google.android.gms.drive.sample.q/home/lakeba13/workspace/DynamicLoading/DynamicLoader/assets/android-demos.apkuickstart.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
 E/MyCrashHandler(29642): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3171)
 E/MyCrashHandler(29642): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3202)
 E/MyCrashHandler(29642): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2540)
 E/MyCrashHandler(29642): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
 E/MyCrashHandler(29642): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
 E/MyCrashHandler(29642): 	at android.os.Handler.dispatchMessage(Handler.java:102)
 E/MyCrashHandler(29642): 	at android.os.Looper.loop(Looper.java:152)
 E/MyCrashHandler(29642): 	at android.app.ActivityThread.main(ActivityThread.java:5497)
 E/MyCrashHandler(29642): 	at java.lang.reflect.Method.invoke(Native Method)
 E/MyCrashHandler(29642): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 E/MyCrashHandler(29642): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by cmzy** [comment]
Could you post more information about it?

**Comment by TamilanPeriyasamy** [comment]
This is sample https://drive.google.com/open?id=0B3y--h4mI7RGdThNNUQxalk0QzA
