### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "java.lang.Object android.util.Singleton.create()"

### ISSUE THREAD

**Issue by JacksonLi-LiBin** [DroidPluginTeam/DroidPlugin#311]
自定义Application里面注册报错
02-13 21:19:57.415 12403-12403/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.yzdsmart.Dingdingwen, PID: 12403
                                                   java.lang.AbstractMethodError: abstract method "java.lang.Object android.util.Singleton.create()"
                                                       at android.util.Singleton.get(Singleton.java:34)
                                                       at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:84)
                                                       at android.app.ActivityThread.createBaseContextForActivity(ActivityThread.java:2444)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2361)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
02-13 21:19:57.415 12403-12403/? E/AndroidRuntime: Error reporting crash
                                                   java.lang.AbstractMethodError: abstract method "java.lang.Object android.util.Singleton.create()"
                                                       at android.util.Singleton.get(Singleton.java:34)
                                                       at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:84)
                                                       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:145)
                                                       at com.morgoo.droidplugin.a.uncaughtException(MyCrashHandler.java:157)
                                                       at cn.jiguang.a.a.b.d.uncaughtException(Unknown Source)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by JacksonLi-LiBin** [comment]
解决了，打包的时候混淆了。

**Comment by fqq1992** [comment]
怎么解决的啊？ 项目不混淆？

**Comment by JacksonLi-LiBin** [comment]
-dontwarn com.morgoo.**
-keep class com.morgoo.** { *; }
