### ISSUE TITLE
AccountManager 需要Hook吗

### ISSUE THREAD

**Issue by wuqi713** [DroidPluginTeam/DroidPlugin#317]
插件应用访问 AccountManager 报错 . AccountManager 需要Hook吗
`java.lang.SecurityException: Uid 10185 is attempting to illegally masquerade as package com.test.lead!
                                                                                       at android.os.Parcel.readException(Parcel.java:1620)
                                                                                       at android.os.Parcel.readException(Parcel.java:1573)
                                                                                       at android.accounts.IAccountManager$Stub$Proxy.getAuthToken(IAccountManager.java:1173)
`

**Comment by cmzy** [comment]
需要自己重新实现的。因为这块的hook我一直没加上。

**Comment by wuqi713** [comment]
@cmzy  好的 已经实现了 Hook AccountManager中的 getAuthToken就解决了
