### ISSUE TITLE
我是用的红米手机4.4.4系统，在这个手机上应用编译通过但是打不开

### ISSUE THREAD

**Issue by wangxp423** [DroidPluginTeam/DroidPlugin#321]
03-09 18:08:49.009 25560-25560/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.airmedia_commute.passenger, PID: 25560
                                                   java.lang.RuntimeException: Unable to get provider com.morgoo.droidplugin.stub.ContentProviderStub$StubP00: java.lang.ClassNotFoundException: Didn't find class "com.morgoo.droidplugin.stub.ContentProviderStub$StubP00" on path: DexPathList[[zip file "/data/app/com.airmedia_commute.passenger-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.airmedia_commute.passenger-1, /vendor/lib, /system/lib]]
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:4889)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4481)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4421)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.morgoo.droidplugin.stub.ContentProviderStub$StubP00" on path: DexPathList[[zip file "/data/app/com.airmedia_commute.passenger-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.airmedia_commute.passenger-1, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:4874)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4481) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4421) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
我这里也报类找不到，在6.0手机可以运行，在我红米4.4.4手机上，打不开，看Log报这个异常。

**Comment by wangxp423** [comment]
造成这个问题的原因是因为我在调用MultiDex.install(this);多包处理的时候，该方法写在了Applicaton的onCreate();里面导致的。正常应该放在attachBaseContext或者直接继承MultiDexApplication。即可。
