### ISSUE TITLE
插件安装成功，但是启动不了（小米MAX 版本是6.0.1）错误日志如下

### ISSUE THREAD

**Issue by xiaoxige** [DroidPluginTeam/DroidPlugin#322]
03-11 13:31:03.566 24586-24586/? E/System: java.io.IOException: No original dex files found for dex location /data/data/cn.xiaoxige.a2017_3_10demo/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-24.2.1_feb5542e57bb0a3f7f97a2f11871848cd60a90bd-classes.dex
                                               at dalvik.system.DexFile.openDexFileNative(Native Method)
                                               at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                                               at dalvik.system.DexFile.<init>(DexFile.java:111)
                                               at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                               at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
                                               at dalvik.system.DexPathList.makePathElements(DexPathList.java:240)
                                               at dalvik.system.DexPathList.<init>(DexPathList.java:120)
                                               at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
                                               at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.<init>(IncrementalClassLoader.java:84)
                                               at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.<init>(IncrementalClassLoader.java:81)
                                               at com.android.tools.fd.runtime.IncrementalClassLoader.createDelegateClassLoader(IncrementalClassLoader.java:111)
                                               at com.android.tools.fd.runtime.IncrementalClassLoader.<init>(IncrementalClassLoader.java:55)
                                               at com.android.tools.fd.runtime.IncrementalClassLoader.inject(IncrementalClassLoader.java:153)
                                               at com.android.tools.fd.runtime.BootstrapApplication.setupClassLoaders(BootstrapApplication.java:180)
                                               at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:236)
                                               at android.app.Application.attach(Application.java:191)
                                               at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                               at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:214)
                                               at com.morgoo.droidplugin.reflect.MethodUtils.invokeMethod(MethodUtils.java:246)
                                               at com.morgoo.droidplugin.core.PluginProcessManager.preMakeApplication(PluginProcessManager.java:272)
                                               at com.morgoo.droidplugin.core.PluginProcessManager.preLoadApk(PluginProcessManager.java:228)
                                               at com.morgoo.droidplugin.hook.handle.PluginCallback.handleLaunchActivity(PluginCallback.java:377)
                                               at com.morgoo.droidplugin.hook.handle.PluginCallback.handleMessage(PluginCallback.java:245)
                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                               at android.os.Looper.loop(Looper.java:148)
                                               at android.app.ActivityThread.main(ActivityThread.java:5442)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
03-11 13:31:03.608 24586-24586/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.TestPlugin:PluginP04, PID: 24586
                                                   java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{cn.xiaoxige.a2017_3_10demo/cn.xiaoxige.a2017_3_10demo.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "cn.xiaoxige.a2017_3_10demo.MainActivity" on path: DexPathList[[zip file "/data/user/0/com.example.TestPlugin/Plugin/cn.xiaoxige.a2017_3_10demo/apk/base-1.apk"],nativeLibraryDirectories=[/data/user/0/com.example.TestPlugin/Plugin/cn.xiaoxige.a2017_3_10demo/lib, /vendor/lib64, /system/lib64]]
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5442)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.xiaoxige.a2017_3_10demo.MainActivity" on path: DexPathList[[zip file "/data/user/0/com.example.TestPlugin/Plugin/cn.xiaoxige.a2017_3_10demo/apk/base-1.apk"],nativeLibraryDirectories=[/data/user/0/com.example.TestPlugin/Plugin/cn.xiaoxige.a2017_3_10demo/lib, /vendor/lib64, /system/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at com.morgoo.droidplugin.core.PluginClassLoader.loadClass(PluginClassLoader.java:74)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5442) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                   	Suppressed: java.lang.ClassNotFoundException: Didn't find class "cn.xiaoxige.a2017_3_10demo.MainActivity" on path: DexPathList[[],nativeLibraryDirectories=[/data/user/0/com.example.TestPlugin/Plugin/cn.xiaoxige.a2017_3_10demo/lib, /vendor/lib64, /system/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                                                       at com.android.tools.fd.runtime.IncrementalClassLoader.findClass(IncrementalClassLoader.java:62)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 13 more
                                                   		Suppressed: java.lang.ClassNotFoundException: Didn't find class "cn.xiaoxige.a2017_3_10demo.MainActivity" on path: DexPathList[[dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-support-annotations-23.1.1_c05f00f2436701be236d57ee18ba0d128eb8015a-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.TestPlugin/files/instant-run/dex/slice-internal_impl-23.1.1_6c83e51e3a63cb865942ef7c07b12f78c1
03-11 13:31:03.703 4767-4772/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
03-11 13:31:03.704 4767-4772/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]

**Comment by asLody** [comment]
Close your InstantRun.

**Comment by xiaoxige** [comment]
今天我把app打包签名后可以了，我想问一下，插件和宿主在测试的时候都需要打包签名吗？还是只需要打包签名一个呢？

**Comment by weijianfeng** [comment]
请问你打包签名的，是宿主还是插件，还是两个都要签名？
