### ISSUE TITLE
魅族 m1 note 机型

### ISSUE THREAD

**Issue by Android-sunshine** [DroidPluginTeam/DroidPlugin#332]
三星smg9350 nexus6 测试都可以跑，一样的程序。魅族 m1 note就不行。
只是个demo程序 跳转Activity  报了ActivityNotFoundException

**Comment by cmzy** [comment]
有完整异常stack么？

**Comment by Android-sunshine** [comment]
03-30 11:05:44.733 796-1635/? W/ActivityManager: getTasks: caller 10242 does not hold REAL_GET_TASKS; limiting output
03-30 11:05:44.966 9571-9571/? W/ADB_SERVICES: create_local_service_socket() name=shell:dumpsys iphonesubinfo
03-30 11:05:44.966 9571-9571/? W/ADB_SERVICES: service_to_fd() name=shell:dumpsys iphonesubinfo
03-30 11:05:44.967 9571-9571/? W/ADB_SERVICES: read_meminfo() mem_free=60964
03-30 11:05:44.968 9571-9571/? W/ADB_SERVICES: create_subproc ret_fd=24 pid=23524
03-30 11:05:44.968 9571-9571/? W/ADB_SERVICES: LS(648592): bound to 'shell:dumpsys iphonesubinfo' via 24
03-30 11:05:44.989 23524-23524/? W/ADB_SERVICES: adb: unable to update oom_score_adj
03-30 11:05:45.005 9571-9571/? W/ADB_SERVICES: entered. LS(648592) fd=24
03-30 11:05:45.700 285-884/? E/AudioALSAPlaybackHandlerBase: openPcmDriver(), pcm_start(0xf24a78a0) fail due to cannot start channel: Broken pipe
03-30 11:05:45.720 796-1547/? W/ActivityManager: getRunningAppProcesses: caller 10245 does not hold REAL_GET_TASKS; limiting output
03-30 11:05:45.711 285-884/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
03-30 11:05:45.712 285-884/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo pcm_get_htimestamp fail, ret = -1, pcm_get_error = cannot start channel: Broken pipe
03-30 11:05:45.735 23384-23384/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.wudi.learnplugin_droidplugin, PID: 23384
                                                   java.lang.IllegalStateException: Could not execute method of the activity
                                                       at android.view.View$1.onClick(View.java:4121)
                                                       at android.view.View.performClick(View.java:4909)
                                                       at android.view.View$PerformClick.run(View.java:20390)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5838)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at android.view.View$1.onClick(View.java:4116)
                                                       at android.view.View.performClick(View.java:4909) 
                                                       at android.view.View$PerformClick.run(View.java:20390) 
                                                       at android.os.Handler.handleCallback(Handler.java:815) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5838) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804) 
                                                    Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.example.yuang.integralwall.main }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1846)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1566)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3830)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3787)
                                                       at android.app.Activity.startActivity(Activity.java:4139)
                                                       at android.app.Activity.startActivity(Activity.java:4069)
                                                       at com.example.wudi.learnplugin_droidplugin.MainActivity.start(MainActivity.java:85)
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at android.view.View$1.onClick(View.java:4116) 
                                                       at android.view.View.performClick(View.java:4909) 
                                                       at android.view.View$PerformClick.run(View.java:20390) 
                                                       at android.os.Handler.handleCallback(Handler.java:815) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5838) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804) 
03-30 11:05:45.737 796-1513/? W/ActivityManager:   Force finishing activity 1 com.example.wudi.learnplugin_droidplugin/.MainActivity
03-30 11:05:45.838 796-1513/? W/ActivityManager: finishTopRunningActivityLocked , taskNdx is 203, activityNdx is 0
03-30 11:05:45.838 796-815/? W/ActivityManager: getTasks: caller 10242 does not hold REAL_GET_TASKS; limiting output
 @cmzy

**Comment by Android-sunshine** [comment]
原因找到了项目配置问题  provider少改了一个  非常抱歉 @cmzy
