### ISSUE TITLE
AlarmService 有bug

### ISSUE THREAD

**Issue by nianzixin** [DroidPluginTeam/DroidPlugin#342]
AndroidRuntime: FATAL EXCEPTION: IntentService[AlarmService]
Process: com.example.TestPlugin:PluginP04, PID: 14038
java.lang.SecurityException: Package com.whatsapp does not belong to 10116
at android.os.Parcel.readException(Parcel.java:1683)
at android.os.Parcel.readException(Parcel.java:1636)
at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:236)
at android.app.AlarmManager.setImpl(AlarmManager.java:671)
at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:884)
at com.whatsapp.AlarmService.b(AlarmService.java:479)
at com.whatsapp.AlarmService.onHandleIntent(AlarmService.java:21152)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:203)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jcxxxxxx** [comment]
Android7.0中AlarmManager对setExact方法进行　calling uid 和 package name 检验。

**Comment by Jcxxxxxx** [comment]
7.0以前AlarmManagerService没有对set方法进行包名校验，在7.0上面需要进行Alarm hook操作，有需要联系我。

**Comment by mosentest** [comment]
> 7.0以前AlarmManagerService没有对set方法进行包名校验，在7.0上面需要进行Alarm hook操作，有需要联系我。

怎么找你
