### ISSUE TITLE
bindService崩溃，OPPO R9 6.0.1

### ISSUE THREAD

**Issue by lyno9527** [DroidPluginTeam/DroidPlugin#350]
java.lang.IllegalArgumentException: method android.app.ActivityManagerProxy.bindService argument 5 has type android.app.IServiceConnection, got com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                                   Caused by: java.lang.IllegalArgumentException: method android.app.ActivityManagerProxy.bindService argument 5 has type android.app.IServiceConnection, got com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(Unknown Source)
                                                                                      at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(Unknown Source)
                                                                                      at com.morgoo.droidplugin.hook.proxy.IActivityManagerHook.invoke(Unknown Source)
                                                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                                      at $Proxy23.bindService(Unknown Source)
                                                                                      at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1327)
                                                                                      at android.app.ContextImpl.bindService(ContextImpl.java:1296)
                                                                                      at android.content.ContextWrapper.bindService(ContextWrapper.java:614)
                                                                                      at com.pingan.plugin.zhiniaolive.zhiniao.manager.ZhiNiaoManager.startZNLiveService(ZhiNiaoManager.java:98)
                                                                                      at com.pingan.plugin.znlive.MainActivity.onCreate(MainActivity.java:14)
                                                                                      at android.app.Activity.performCreate(Activity.java:6323)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                      at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(Unknown Source)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by lyno9527** [comment]
@cmzy
