### ISSUE TITLE
有数据库apk的不能加载吗？

### ISSUE THREAD

**Issue by ryanz91** [DroidPluginTeam/DroidPlugin#351]
E/SQLiteDatabase: Failed to open database '/data/data/com.xxx.xxx/databases/cc/cc.db'.
                                                                                    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
                                                                                        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
                                                                                        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
                                                                                        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:719)
                                                                                        at u.aly.e.openOrCreateDatabase(UMCCPathDatabaseContext.java:44)
                                                                                        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                                        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                        at u.aly.c.<init>(UMCCDBHelper.java:1058)
                                                                                        at u.aly.c.<init>(UMCCDBHelper.java:46)
                                                                                        at u.aly.c.<init>(UMCCDBHelper.java:18)
                                                                                        at u.aly.c$a.<clinit>(UMCCDBHelper.java:24)
                                                                                        at u.aly.c.a(UMCCDBHelper.java:30)
                                                                                        at u.aly.b.b(DatabaseManager.java:27)
                                                                                        at u.aly.b.a(DatabaseManager.java:33)
                                                                                        at u.aly.m$6.a(UMCCAggregatedManager.java:1058)
                                                                                        at com.umeng.analytics.g.run(SafeRunnable.java:8)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                        at java.lang.Thread.run(Thread.java:761)

**Comment by godwilling** [comment]
帮顶，同问。

**Comment by godwilling** [comment]
可以加载，我弄错了。

**Comment by ryanz91** [comment]
@godwilling 怎么回事？

**Comment by yeyutianya** [comment]
有没有试过4.x系统能打开不

**Comment by CaptainJno** [comment]
请问，你们的问题解决没？
@ryanz91 @godwilling

**Comment by CaptainJno** [comment]
@godwilling 你好，请问这个问题你是怎么解决的
