### ISSUE TITLE
插件App中使用友盟数据库时，出现错误，请问如何解决？

### ISSUE THREAD

**Issue by weijianfeng** [DroidPluginTeam/DroidPlugin#377]
PluginP08 E/SQLiteDatabase: Failed to open database '/data/data/xxxxx/databases/ua.db'.
                                                                                  android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                      at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
                                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
                                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
                                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
                                                                                      at com.umeng.analytics.pro.r.openOrCreateDatabase(UMDBCreater.java:174)
                                                                                      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                                      at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                      at com.umeng.analytics.pro.u.a(UMDBManager.java:41)
                                                                                      at com.umeng.analytics.pro.w.a(UMStoreManager.java:155)
                                                                                      at com.umeng.analytics.pro.bf.a(ViewPageTracker.java:88)
                                                                                      at com.umeng.analytics.b.i(InternalAgent.java:277)
                                                                                      at com.umeng.analytics.b.b(InternalAgent.java:46)
                                                                                      at com.umeng.analytics.b$3.a(InternalAgent.java:194)
                                                                                      at com.umeng.analytics.pro.cb.run(SafeRunnable.java:8)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                      at java.lang.Thread.run(Thread.java:761)

**Comment by CaptainJno** [comment]
@weijianfeng   我也遇到和你类似的错误了，打开数据库报错。我的只在魅族手机上出现。请问你解决没？

**Comment by magiclonw** [comment]
/data/data/插件宿主包名/Plugin/插件包名/data/插件包名    这样才是正确的路径

**Comment by ALexBoy123** [comment]
@weijianfeng 最后怎么解决的，能提供一下方法吗
