### ISSUE TITLE
java.lang.NoSuchMethodException: generatePackageInfo

### ISSUE THREAD

**Issue by JAYE123** [DroidPluginTeam/DroidPlugin#393]
09-05 18:16:26.116 18473-18473/com.example.TestPlugin I/PackageParserApi21: get generatePackageInfo 1 failjava.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, interface java.util.Set, class android.content.pm.PackageUserState, int]
                                                                                at java.lang.Class.getConstructorOrMethod(Class.java:472)
                                                                                at java.lang.Class.getMethod(Class.java:857)
                                                                                at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
                                                                                at com.morgoo.droidplugin.pm.parser.PackageParserApi21.generatePackageInfo(PackageParserApi21.java:190)
                                                                                at com.morgoo.droidplugin.pm.parser.PluginPackageParser.getPackageInfo(PluginPackageParser.java:364)
                                                                                at com.morgoo.droidplugin.pm.IPluginManagerImpl.getInstalledPackages(IPluginManagerImpl.java:548)
                                                                                at com.morgoo.droidplugin.pm.PluginManager.getInstalledPackages(PluginManager.java:487)
                                                                                at com.example.TestPlugin.InstalledFragment.onListItemClick(InstalledFragment.java:55)
                                                                                at com.example.TestPlugin.InstalledFragment$3$1.onClick(InstalledFragment.java:174)
                                                                                at android.view.View.performClick(View.java:4768)
                                                                                at android.view.View$PerformClick.run(View.java:19073)
                                                                                at android.os.Handler.handleCallback(Handler.java:755)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:145)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5266)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
                                                                                at dalvik.system.NativeStart.main(Native Method)
09-05 18:16:26.126 18473-18473/com.example.TestPlugin I/HomeFragment: start: -----已安装插件
09-05 18:16:26.126 18473-18473/com.example.TestPlugin I/HomeFragment: start: -----path_plugin:/data/data/com.example.TestPlugin/Plugin/com.qqreader.schoollibrary/apk/base-1.apk

**Comment by cmzy** [comment]
请提供android版本号，手机型号等信息。

**Comment by JAYE123** [comment]
魅蓝metal 系统版本5.1  下载来直接运行没问题，点击安装插件apk也没问题，插件apk是一个空项目，就是打开插件报的这个错误，然后程序退出，麻烦大神看看什么原因？

**Comment by 284361303** [comment]
/PackageParserApi21: get generatePackageInfo 1 failjava.lang.NoSuchMethodException: generatePackageInfo [class android.content.pm.PackageParser$Package, class [I, int, long, long, interface java.util.Set, class android.content.pm.PackageUserState, int]
                                                           at java.lang.Class.getMethod(Class.java:665)
                                                           at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
                                                           at com.morgoo.droidplugin.pm.parser.PackageParserApi21.generatePackageInfo(PackageParserApi21.java:190)
                                                           at com.morgoo.droidplugin.pm.parser.PluginPackageParser.getPackageInfo(PluginPackageParser.java:364)
                                                           at com.morgoo.droidplugin.pm.IPluginManagerImpl.installPackage(IPluginManagerImpl.java:880)
                                                           at com.morgoo.droidplugin.pm.PluginManager.installPackage(PluginManager.java:874)
                                                           at com.example.TestPlugin.MainActivity.doInstall(MainActivity.java:58)
                                                           at com.example.TestPlugin.MainActivity.access$000(MainActivity.java:24)
                                                           at com.example.TestPlugin.MainActivity$1.run(MainActivity.java:35)
12-21 09:53:22.516 20083-20125/? I/IPluginManagerImpl: Save com.example.newdroidplugin signature of 0,md5=4B55338A2A3BA3EA0BF94AE399D898EF
一直报这个错误，不知道什么原因，子项目有的是可以，有的是不行，不知道里面有什么东西不支持吗，求楼主给予回复……

**Comment by sebandres** [comment]
This is rather late but I don't think this is anything to worry about, if you look at the code where this is thrown it actually tries to get the method in 3 different ways, this is just to tell you that attempt `1` failed. 

If this is the only message you see it should mean that the second way of getting it actually worked.
