### ISSUE TITLE
8.0运行新改的PluginPackageParser代码会报错

### ISSUE THREAD

**Issue by zzf61** [DroidPluginTeam/DroidPlugin#394]
PluginPackageParser 新增的对android n以上的版本加的判断处理会报错的，具体看堆栈

android.os.RemoteException: Cannot locate declared field android.content.pm.ApplicationInfo.deviceEncryptedDataDir
09-07 15:58:47.079 11231 13043 W System.err: 	at com.morgoo.droidplugin.reflect.Validate.isTrue(Validate.java:32)
09-07 15:58:47.080 11231 13043 W System.err: 	at com.morgoo.droidplugin.reflect.FieldUtils.writeField(FieldUtils.java:166)
09-07 15:58:47.080 11231 13043 W System.err: 	at com.morgoo.droidplugin.reflect.FieldUtils.writeField(FieldUtils.java:159)
09-07 15:58:47.080 11231 13043 W System.err: 	at com.morgoo.droidplugin.pm.parser.PluginPackageParser.fixApplicationInfo(PluginPackageParser.java:465)
09-07 15:58:47.080 11231 13043 W System.err: 	at com.morgoo.droidplugin.pm.parser.PluginPackageParser.<init>(PluginPackageParser.java:106)
09-07 15:58:47.080 11231 13043 W System.err: 	at com.morgoo.droidplugin.pm.IPluginManagerImpl.installPackage(IPluginManagerImpl.java:838)
09-07 15:58:47.080 11231 13043 W System.err: 	at com.morgoo.droidplugin.pm.PluginManager.installPackage(PluginManager.java:874)

**Comment by icepeach1220** [comment]
解决了吗？我也有同样的问题
