### ISSUE TITLE
8.0报错 ClassNotFoundException: android.os.storage.IMountService$Stub

### ISSUE THREAD

**Issue by yeyutianya** [DroidPluginTeam/DroidPlugin#397]
09-13 09:42:55.313 5098-5098/? E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-37ms what=100 obj=ActivityRecord{15504a0 token=android.os.BinderProxy@c5be859 {com.huawei.genexcloud/com.morgoo.droidplugin.stub.ActivityStub$P07$Standard00}} target=android.app.ActivityThread$H }
09-13 09:42:55.357 5098-5098/? E/HookFactory: installHook com.morgoo.droidplugin.hook.binder.IMountServiceBinderHook@82d5d0 errorjava.lang.ClassNotFoundException: android.os.storage.IMountService$Stub
                                                  at java.lang.Class.classForName(Native Method)
                                                  at java.lang.Class.forName(Class.java:453)
                                                  at java.lang.Class.forName(Class.java:378)
                                                  at com.morgoo.helper.compat.IMountServiceCompat.asInterface(IMountServiceCompat.java:45)
                                                  at com.morgoo.droidplugin.hook.binder.IMountServiceBinderHook.getOldObj(IMountServiceBinderHook.java:45)
                                                  at com.morgoo.droidplugin.hook.binder.BinderHook.onInstall(BinderHook.java:118)
                                                  at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:115)
                                                  at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:135)
                                                  at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:313)
                                                  at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:80)
                                                  at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:64)

  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.storage.IMountService$Stub" on path: DexPathList[[zip file "/data/app/com.huawei.genexcloud-VGNZ2_R_w-NpGKq8B08pbg==/base.apk"],nativeLibraryDirectories=[/data/app/com.huawei.genexcloud-VGNZ2_R_w-NpGKq8B08pbg==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                  at java.lang.Class.classForName(Native Method) 
                                                  at java.lang.Class.forName(Class.java:453) 
                                                  at java.lang.Class.forName(Class.java:378) 
                                                  at com.morgoo.helper.compat.IMountServiceCompat.asInterface(IMountServiceCompat.java:45) 
                                                  at com.morgoo.droidplugin.hook.binder.IMountServiceBinderHook.getOldObj(IMountServiceBinderHook.java:45) 
                                                  at com.morgoo.droidplugin.hook.binder.BinderHook.onInstall(BinderHook.java:118) 
                                                  at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:115) 
                                                  at com.morgoo.droidplugin.hook.HookFactory.installHook(HookFactory.java:135) 
                                                  at com.morgoo.droidplugin.core.PluginProcessManager.installHook(PluginProcessManager.java:313) 
                                                  at com.morgoo.droidplugin.PluginHelper.initPlugin(PluginHelper.java:80) 
                                                  at com.morgoo.droidplugin.PluginHelper.applicationOnCreate(PluginHelper.java:64)

**Comment by yeyutianya** [comment]
@cmzy 帮忙看下吧。用最新的dp代码，简单的插件可以运行，带有so文件的插件，运行崩溃。

**Comment by TwoBiAndroid** [comment]
@yeyutianya 说明文档已经说了，缺乏对native的hook

**Comment by wx2013** [comment]
8.0以下都没问题
目前手上一款华为8.0系统的也是报这个错

**Comment by howtoplay** [comment]
你好，请问你这个问题解决了吗？
