### ISSUE TITLE
成功加载插件后，打开插件时发生崩溃

### ISSUE THREAD

**Issue by jessehev** [DroidPluginTeam/DroidPlugin#408]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.cocos2d.fishingjoy3/org.cocos2d.fishingjoy3.FishingJoy3Activity}: java.lang.ClassNotFoundException: org.cocos2d.fishingjoy3.FishingJoy3Activity
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1983)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFound

**Comment by jessehev** [comment]
java.lang.ClassNotFound ，但是不晓得是什么原因引起的

**Comment by skydsai** [comment]
我也是一样，错误日志如下：
