### ISSUE TITLE
华为Mate10 兼容性问题

### ISSUE THREAD

**Issue by SheepYoung** [DroidPluginTeam/DroidPlugin#416]
华为Mate 10 Api level: 26
看了下日子,好像是启动Service失败了: 
15:22:38.580 17561 17561 E AbstractServiceStub: **handleExceptionjava.lang.NoSuchMethodException: handleCreateService [class android.app.ActivityThread$CreateServiceData]**
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at java.lang.Class.getMethod(Class.java:2068)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at com.morgoo.droidplugin.stub.ServcesManager.handleCreateServiceOne(ServcesManager.java:130)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at com.morgoo.droidplugin.stub.ServcesManager.onStart(ServcesManager.java:247)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at com.morgoo.droidplugin.stub.AbstractServiceStub.onStart(AbstractServiceStub.java:86)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.app.Service.onStartCommand(Service.java:505)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4008)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.app.ActivityThread.-wrap21(Unknown Source:0)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.os.Handler.dispatchMessage(Handler.java:108)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.os.Looper.loop(Looper.java:166)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at android.app.ActivityThread.main(ActivityThread.java:7358)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at java.lang.reflect.Method.invoke(Native Method)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
11-17 15:22:38.580 17561 17561 E AbstractServiceStub: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)

[华为Mate_10_realtime_new.log](https://github.com/DroidPluginTeam/DroidPlugin/files/1481421/Mate_10_realtime_new.log)

**Comment by smile3670** [comment]
华为Mate 10 handleCreateService 函数增加了一个int参数，多传一个int参数，服务就启来了
Method method = activityThread.getClass().getDeclaredMethod("handleCreateService", CreateServiceData, int.class);

**Comment by SheepYoung** [comment]
@smile3670 这个我也加了, 只解决了启动问题, 好像还有其他兼容性问题, 估计华为不单单改了一个方法

**Comment by wx2013** [comment]
int 参数传什么值?
目前在做8.0的适配,只有华为一款8.0的手机
8.0一直无法启动成功
