### ISSUE TITLE
打开插（插件中进行了bindservice的）件，出现RuntimeException异常，求指导！

### ISSUE THREAD

**Issue by a40255478** [DroidPluginTeam/DroidPlugin#427]
--------------------------------------
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hnebang.ebchatdemo/com.hnebang.ebchat.ui.MainActivity}: java.lang.IllegalArgumentException: method android.app.IActivityManager.bindService argument 5 has type android.app.IServiceConnection, got com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: java.lang.IllegalArgumentException: method android.app.IActivityManager.bindService argument 5 has type android.app.IServiceConnection, got com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1
	at java.lang.reflect.Method.invoke(Native Method)
	at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:52)
	at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(ProxyHook.java:60)
	at com.morgoo.droidplugin.hook.proxy.IActivityManagerHook.invoke(IActivityManagerHook.java:63)
	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
	at $Proxy28.bindService(Unknown Source)
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1633)
	at android.app.ContextImpl.bindService(ContextImpl.java:1592)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
	at com.hnebang.ebchat.ui.MainActivity.initServer(MainActivity.java:203)
	at com.hnebang.ebchat.ui.MainActivity.onCreate(MainActivity.java:141)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	... 9 more
java.lang.IllegalArgumentException: method android.app.IActivityManager.bindService argument 5 has type android.app.IServiceConnection, got com.morgoo.droidplugin.hook.handle.IActivityManagerHookHandle$bindService$1
	at java.lang.reflect.Method.invoke(Native Method)
	at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:52)
	at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(ProxyHook.java:60)
	at com.morgoo.droidplugin.hook.proxy.IActivityManagerHook.invoke(IActivityManagerHook.java:63)
	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
	at $Proxy28.bindService(Unknown Source)
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1633)
	at android.app.ContextImpl.bindService(ContextImpl.java:1592)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
	at com.hnebang.ebchat.ui.MainActivity.initServer(MainActivity.java:203)
	at com.hnebang.ebchat.ui.MainActivity.onCreate(MainActivity.java:141)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
--------------------------------------

**Comment by icepeach1220** [comment]
我也遇到同样的问题，你做出来啦吗

**Comment by a40255478** [comment]
做出来也意义不大了，不支持Android9.0

2019-06-19 



me_message 



发件人： icepeach1220 
发送时间： 2019-06-19  11:24:06 
收件人： DroidPluginTeam/DroidPlugin 
抄送： a40255478; Author 
主题： Re:_[DroidPluginTeam/DroidPlugin]_打开插（插件中进行了bindservice的）件，出现RuntimeException异常，求指导！_(#427) 
 
我也遇到同样的问题，你做出来啦吗

**Comment by icepeach1220** [comment]
> 做出来也意义不大了，不支持Android9.0 2019-06-19 me_message 发件人： icepeach1220 发送时间： 2019-06-19 11:24:06 收件人： DroidPluginTeam/DroidPlugin 抄送： a40255478; Author 主题： Re:_[DroidPluginTeam/DroidPlugin]_打开插（插件中进行了bindservice的）件，出现RuntimeException异常，求指导！_(#427) 我也遇到同样的问题，你做出来啦吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

意思是改了这个还有其他很多问题？

**Comment by a40255478** [comment]
是的。。。


2019-06-19 



me_message 



发件人： icepeach1220 
发送时间： 2019-06-19  13:58:04 
收件人： DroidPluginTeam/DroidPlugin 
抄送： a40255478; Author 
主题： Re:_[DroidPluginTeam/DroidPlugin]_打开插（插件中进行了bindservice的）件，出现RuntimeException异常，求指导！_(#427) 
 
做出来也意义不大了，不支持Android9.0 2019-06-19 me_message 发件人： icepeach1220 发送时间： 2019-06-19 11:24:06 收件人： DroidPluginTeam/DroidPlugin 抄送： a40255478; Author 主题： Re:_[DroidPluginTeam/DroidPlugin]打开插（插件中进行了bindservice的）件，出现RuntimeException异常，求指导！(#427) 我也遇到同样的问题，你做出来啦吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
意思是改了这个还有其他很多问题？

**Comment by icepeach1220** [comment]
OK，谢了

**Comment by icepeach1220** [comment]
那你有没有在Android9.0上试过其他的动态加载呢？
