### ISSUE TITLE
华为8.0报错

### ISSUE THREAD

**Issue by wx2013** [DroidPluginTeam/DroidPlugin#432]
目前就手上一款8.0手机,并且是华为的
更新到最新的代码之后发现8.0以下的手机没问题,就8.0的手机出现问题
1.ClassNotFoundException: android.os.storage.IMountService$Stub
https://github.com/DroidPluginTeam/DroidPlugin/issues/397

出现这个问题之后,我先把 IMountService这HOOK 点注释了
于是出现了
2. handleExceptionjava.lang.NoSuchMethodException: handleCreateService [class android.app.ActivityThread$CreateServiceData]
https://github.com/DroidPluginTeam/DroidPlugin/issues/416
添加了 Int.class 后又出现了新的问题
 E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                               java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
                                                                   at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:60)
                                                                   at android.os.Binder.execTransact(Binder.java:675)
03-12 16:54:04.069 32296-32311/com.esbook.reader E/JavaBinder: java.lang.Error thrown during binder transaction (stack trace follows) : 

可见华为8.0把底层修改的有点多啊..
暂时不知道解决方案

**Comment by xubobojian** [comment]
华为手机今天8.0越来越多了，大佬有空记得弄下呀

**Comment by howtoplay** [comment]
你好，我也遇到这个问题了，请问你解决了吗？

**Comment by wx2013** [comment]
> 你好，我也遇到这个问题了，请问你解决了吗？

replugin 换这个

**Comment by ling976** [comment]
![image](https://user-images.githubusercontent.com/63000347/81521316-5be0b380-9379-11ea-969d-528764fec25b.png)
这个遇到过吗
