### ISSUE TITLE
使用jks签名后的apk无法启动，默认debug可以正常启动

### ISSUE THREAD

**Issue by GoloGulo** [DroidPluginTeam/DroidPlugin#449]
12-25 23:24:59.595 19369-19369/? E/c: installHook com.morgoo.droidplugin.f.g.a@2cb1e3c8 errorjava.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.morgoo.droidplugin.h.c.a()
        at com.morgoo.droidplugin.h.c.a()
        at b.h.a.f.a.b()
        at com.morgoo.droidplugin.f.g.a.a()
        at com.morgoo.droidplugin.f.c.a()
        at com.morgoo.droidplugin.f.c.a()
        at com.morgoo.droidplugin.e.c.d()
        at com.morgoo.droidplugin.b.c()
        at com.morgoo.droidplugin.b.b()
        at com.sw.gtx.app.AppApplication.onCreate()
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
        at android.app.ActivityThread.access$1600(ActivityThread.java:136)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1257)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5045)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.AbstractMethodError: abstract method not implemented
        at android.util.Singleton.create(Singleton.java)
        at android.util.Singleton.get(Singleton.java:34)
        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:76)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.morgoo.droidplugin.h.c.a() 
        at com.morgoo.droidplugin.h.c.a() 
        at b.h.a.f.a.b() 
        at com.morgoo.droidplugin.f.g.a.a() 
        at com.morgoo.droidplugin.f.c.a() 
        at com.morgoo.droidplugin.f.c.a() 
        at com.morgoo.droidplugin.e.c.d() 
        at com.morgoo.droidplugin.b.c() 
        at com.morgoo.droidplugin.b.b() 
        at com.sw.gtx.app.AppApplication.onCreate() 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:136) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1257) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5045) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660) 
        at dalvik.system.NativeStart.main(Native Method) 
12-25 23:24:59.606 19369-19369/? E/b: setHookEnable has errorjava.lang.AbstractMethodError: abstract method not implemented
        at android.util.Singleton.create(Singleton.java)
        at android.util.Singleton.get(Singleton.java:34)
        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:76)
        at android.app.ActivityManager.getRunningAppProcesses(ActivityManager.java:1877)
        at com.morgoo.droidplugin.e.c.b()
        at com.morgoo.droidplugin.e.c.e()
        at com.morgoo.droidplugin.b.c()
        at com.morgoo.droidplugin.b.b()
        at com.sw.gtx.app.AppApplication.onCreate()
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
        at android.app.ActivityThread.access$1600(ActivityThread.java:136)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1257)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5045)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
        at dalvik.system.NativeStart.main(Native Method)
12-25 23:24:59.609 19369-19369/? E/b: installHook has errorjava.lang.AbstractMethodError: abstract method not implemented
        at android.util.Singleton.create(Singleton.java)
        at android.util.Singleton.get(Singleton.java:34)
        at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:76)
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1634)
        at android.app.ContextImpl.startService(ContextImpl.java:1616)
        at com.morgoo.droidplugin.g.e.a()
        at com.morgoo.droidplugin.g.e.a()
        at com.morgoo.droidplugin.b.c()
        at com.morgoo.droidplugin.b.b()
        at com.sw.gtx.app.AppApplication.onCreate()
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
        at android.app.ActivityThread.access$1600(ActivityThread.java:136)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1257)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5045)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by GoloGulo** [comment]
添加了混淆之后，Hook的enable设置为true之后，又出现这个异常

12-25 23:53:43.975 25271-25271/? E/CustomActivityOnCrash: IMPORTANT WARNING! You already have an UncaughtExceptionHandler, are you sure this is correct? If you use a custom UncaughtExceptionHandler, you must initialize it AFTER CustomActivityOnCrash! Installing anyway, but your original handler will not be called.
12-25 23:53:43.999 25271-25271/? E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-68ms what=100 obj=ActivityRecord{2ca75160 token=android.os.BinderProxy@2c8977b8 {com.sw.gtx/com.sw.gtx.ui.splash.SplashActivity}} target=android.app.ActivityThread$H }
12-25 23:53:44.016 25271-25271/? E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@2ca46f10,new=android.app.ActivityManagerProxy@2ca46f10
12-25 23:53:44.209 25271-25271/com.sw.gtx E/ottlogin: E<20191225235344>[jni/base/network/icntvHttp.cpp-106]: CURLINFO_RESPONSE_CODE : 200
12-25 23:53:44.217 25271-25271/com.sw.gtx A/libc: Fatal signal 11 (SIGSEGV) at 0x0000002c (code=1), thread 25271 (com.sw.gtx)
12-25 23:53:44.731 25307-25307/? E/CustomActivityOnCrash: IMPORTANT WARNING! You already have an UncaughtExceptionHandler, are you sure this is correct? If you use a custom UncaughtExceptionHandler, you must initialize it AFTER CustomActivityOnCrash! Installing anyway, but your original handler will not be called.
12-25 23:53:44.759 25307-25307/com.sw.gtx E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-60ms what=100 obj=ActivityRecord{2c8b6128 token=android.os.BinderProxy@2ca81a70 {com.sw.gtx/com.sw.gtx.ui.splash.SplashActivity}} target=android.app.ActivityThread$H }
12-25 23:53:44.782 25307-25307/com.sw.gtx E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@2ca6d858,new=android.app.ActivityManagerProxy@2ca6d858
12-25 23:53:45.020 25307-25307/com.sw.gtx E/ottlogin: E<20191225235345>[jni/base/network/icntvHttp.cpp-106]: CURLINFO_RESPONSE_CODE : 200
12-25 23:53:45.022 25307-25307/com.sw.gtx A/libc: Fatal signal 11 (SIGSEGV) at 0x0000002c (code=1), thread 25307 (com.sw.gtx)

**Comment by GoloGulo** [comment]
没有错误信息，启动直接crush
12-26 00:13:05.380 7721-7721/? E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-43ms what=140 arg1=10 target=android.app.ActivityThread$H }
12-26 00:13:05.390 7721-7721/? E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@418a1278,new=android.app.ActivityManagerProxy@418a1278
