### ISSUE TITLE
7.1.2设备启动崩溃

### ISSUE THREAD

**Issue by ling976** [DroidPluginTeam/DroidPlugin#455]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.banyan.platform/com.banyan.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.IWindowManager.hasNavigationBar()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6297)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.IWindowManager.hasNavigationBar()' on a null object reference
        at android.view.ViewConfiguration.<init>(ViewConfiguration.java:320)
        at android.view.ViewConfiguration.get(ViewConfiguration.java:369)
        at android.view.View.<init>(View.java:4064)
        at android.view.View.<init>(View.java:4198)
        at android.view.ViewGroup.<init>(ViewGroup.java:604)
        at android.view.ViewGroup.<init>(ViewGroup.java:600)
        at android.view.ViewGroup.<init>(ViewGroup.java:596)
        at android.view.ViewGroup.<init>(ViewGroup.java:592)
        at android.widget.FrameLayout.<init>(FrameLayout.java:95)
        at com.android.internal.policy.DecorView.<init>(DecorView.java:247)
        at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2311)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2654)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2077)
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:158)
        at android.app.Activity.performCreateCommon(Activity.java:6676)
        at android.app.Activity.performCreate(Activity.java:6683)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at com.morgoo.droidplugin.hook.handle.PluginInstrumentation.callActivityOnCreate(PluginInstrumentation.java:110)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)?
        at android.app.ActivityThread.-wrap12(ActivityThread.java)?
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)?
        at android.os.Handler.dispatchMessage(Handler.java:110)?
        at android.os.Looper.loop(Looper.java:203)?
        at android.app.ActivityThread.main(ActivityThread.java:6297)?
        at java.lang.reflect.Method.invoke(Native Method)?
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)?

**Comment by xiaoming6672** [comment]
和你一样的问题，7以上的启动，有涉及到setContentView的地方，全是报这个崩溃错误
