### ISSUE TITLE
安装插件失败

### ISSUE THREAD

**Issue by Timan86** [DroidPluginTeam/DroidPlugin#457]
W/System.err: android.os.RemoteException: collectCertificates [class android.content.pm.PackageParser$Package, int]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getMethod(Class.java:1690)
        at com.morgoo.droidplugin.reflect.MethodUtils.getAccessibleMethod(MethodUtils.java:143)
        at com.morgoo.droidplugin.pm.parser.PackageParserApi21.collectCertificates(PackageParserApi21.java:114)
        at com.morgoo.droidplugin.pm.parser.PluginPackageParser.collectCertificates(PluginPackageParser.java:232)
        at com.morgoo.droidplugin.pm.IPluginManagerImpl.installPackage(IPluginManagerImpl.java:879)
        at com.morgoo.droidplugin.pm.PluginManager.installPackage(PluginManager.java:874)
        at com.example.TestPlugin.ApkFragment.doInstall(ApkFragment.java:290)
        at com.example.TestPlugin.ApkFragment.access$100(ApkFragment.java:37)
        at com.example.TestPlugin.ApkFragment$5.run(ApkFragment.java:261)
    Caused by: java.lang.NoSuchMethodException: collectCertificates [class android.content.pm.PackageParser$Package, int]

**Comment by cyber-proxy** [comment]
需要签名
