### ISSUE TITLE
android9.0启动插件卡住

### ISSUE THREAD

**Issue by Timan86** [DroidPluginTeam/DroidPlugin#459]
2020-05-08 16:51:35.970 13660-13660/com.example.TestPlugin:PluginP06 E/Instrumentation: Uninitialized ActivityThread, likely app-created Instrumentation, disabling AppComponentFactory
    java.lang.Throwable
        at android.app.Instrumentation.getFactory(Instrumentation.java:1233)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by sihua007** [comment]
请问你解决了吗

**Comment by Timan86** [comment]
这是哪个第三方 忘记了



---原始邮件---
发件人: "sihua007"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 中午1:45
收件人: "DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&gt;;
抄送: "Timan86"<728297940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)




 
请问你解决了吗

**Comment by sihua007** [comment]
DroidPlugin插件，方便加一下qq吗3546586311


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Timan86"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午3:36
收件人:&nbsp;"DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&gt;;
抄送:&nbsp;"司华-15966629267"<240698138@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)





 这是哪个第三方 忘记了 
 
 
 
 ---原始邮件--- 
 发件人: "sihua007"<notifications@github.com&amp;gt; 
 发送时间: 2020年7月2日(周四) 中午1:45 
 收件人: "DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&amp;gt;; 
 抄送: "Timan86"<728297940@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459) 
 
 
 
 
   
 请问你解决了吗

**Comment by Timan86** [comment]
发我地址看看



---原始邮件---
发件人: "sihua007"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 下午3:38
收件人: "DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&gt;;
抄送: "Timan86"<728297940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)




 DroidPlugin插件，方便加一下qq吗3546586311 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Timan86"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年7月2日(星期四) 下午3:36 
 收件人:&amp;nbsp;"DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"司华-15966629267"<240698138@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459) 
 
 
 
 
 
  这是哪个第三方 忘记了  
   
   
   
  ---原始邮件---  
  发件人: "sihua007"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年7月2日(周四) 中午1:45  
  收件人: "DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&amp;amp;gt;;  
  抄送: "Timan86"<728297940@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题: Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)  
   
   
   
   
     
  请问你解决了吗

**Comment by sihua007** [comment]
https://github.com/DroidPluginTeam/DroidPlugin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Timan86"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午3:40
收件人:&nbsp;"DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&gt;;
抄送:&nbsp;"司华-15966629267"<240698138@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)





 发我地址看看 
 
 
 
 ---原始邮件--- 
 发件人: "sihua007"<notifications@github.com&amp;gt; 
 发送时间: 2020年7月2日(周四) 下午3:38 
 收件人: "DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&amp;gt;; 
 抄送: "Timan86"<728297940@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题: Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459) 
 
 
 
 
  DroidPlugin插件，方便加一下qq吗3546586311  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"Timan86"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年7月2日(星期四) 下午3:36  
  收件人:&amp;amp;nbsp;"DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"司华-15966629267"<240698138@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)  
   
   
   
   
   
   这是哪个第三方 忘记了   
     
     
     
   ---原始邮件---   
   发件人: "sihua007"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年7月2日(周四) 中午1:45   
   收件人: "DroidPluginTeam/DroidPlugin"<DroidPlugin@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "Timan86"<728297940@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题: Re: [DroidPluginTeam/DroidPlugin] android9.0启动插件卡住 (#459)   
     
     
     
     
       
   请问你解决了吗
